---  Variables, don't need translated ---
TITAN_MODMENU_LOC_US = "enUS";
TITAN_MODMENU_LOC_DE = "krKR";
TITAN_MODMENU_LOC_FR = "frFR";
TITAN_MODMENU_SPACER = 42;

---     English     ---
--- by Tekkub (duh) ---
TITAN_MODMENU_MENU_BARTEXT = "위드(WiD)메뉴";
TITAN_MODMENU_MENU_TEXT = "위드(WiD)메뉴";
TITAN_MODMENU_MENU_OPENTEXT = "애드온 열기";
TITAN_MODMENU_MENU_SETUPTEXT= "애드온 설정";
TITAN_MODMENU_MENU_SYSTEMTEXT = "시스템메뉴";


TITAN_MODMENU_TRADE_SPELLBOOKGENERAL = "일반";
TITAN_MODMENU_TRADE_FINDHERB = "약초 찾기";
TITAN_MODMENU_TRADE_FINDORE = "광물 찾기";
TITAN_MODMENU_TRADE_FIRSTAID = "응급치료";
TITAN_MODMENU_TRADE_HERB = "약초 채집";
TITAN_MODMENU_TRADE_MINING = "채광";
TITAN_MODMENU_TRADE_ALCHEMY = "연금술";
TITAN_MODMENU_TRADE_TAILOR = "재봉술";
TITAN_MODMENU_TRADE_BLACKSMITH = "대장 기술";
TITAN_MODMENU_TRADE_ENGINEER = "기계 공학";
TITAN_MODMENU_TRADE_LEATHER = "가죽 세공술";
TITAN_MODMENU_TRADE_SKINNING = "무두질";
TITAN_MODMENU_TRADE_ENCHANTING = "마법부여";
TITAN_MODMENU_TRADE_DISENCHANTING = "마력 추출";
TITAN_MODMENU_TRADE_COOKING = "요리";
TITAN_MODMENU_TRADE_FISHING = "낚시";


TITAN_MODMENU_CAT_RAID = "위드(WiD) 각 기능 설정";
TITAN_MODMENU_CAT_OTHER = "기타 UI 모드";
TITAN_MODMENU_CAT_HANDY = "간단 주사위";
TITAN_MODMENU_CAT_TRADESKILLS = "전문/보조 기술";
TITAN_MODMENU_CAT_EMOTES = "감정 표현";
TITAN_MODMENU_CAT_GAMEMENU = "게임 메뉴";
TITAN_MODMENU_CAT_SYSTEM = "시스템 메뉴";
TITAN_MODMENU_CAT_MMSETTINGS = "모드메뉴 설정";


TITAN_MODMENU_KEY = "단축키 설정";
TITAN_MODMENU_SETUP = "설정";
TITAN_MODMENU_TOGGLE = "전환";
TITAN_MODMENU_OPEN = "열기";
TITAN_MODMENU_CLOSE = "닫기";
TITAN_MODMENU_SHOW = "보이기";
TITAN_MODMENU_HIDE = "감추기";
TITAN_MODMENU_LOCK = "잠금";
TITAN_MODMENU_UNLOCK = "잠금 해제";
TITAN_MODMENU_HELP = "도움말";
TITAN_MODMENU_ON = "켜기";
TITAN_MODMENU_OFF = "끄기";
TITAN_MODMENU_ENABLE = "활성화";
TITAN_MODMENU_DISABLE = "비활성화";
TITAN_MODMENU_RESET = "초기화";
TITAN_MODMENU_OPTIONS = "설정";
TITAN_MODMENU_BUTTON = "버튼";
TITAN_MODMENU_VIEW = "View";
TITAN_MODMENU_AUTOMATIC = "Automatic";
TITAN_MODMENU_STATUS = "Status";
TITAN_MODMENU_DISPLAY = "Display";
TITAN_MODMENU_MINIMAP = "미니맵";
TITAN_MODMENU_TOGGLEICONTEXT = "아이콘/텍스트전환";
TITAN_MODMENU_LOGOUT = "접속 종료";
TITAN_MODMENU_EXIT = "게임 종료";
TITAN_MODMENU_EXIT1 = "/exit";
TITAN_MODMENU_GM = "도움 요청";
TITAN_MODMENU_SPELL = "마법책과 능력";
TITAN_MODMENU_QUEST = "퀘스트 목록";
TITAN_MODMENU_WORLD = "세계 지도";
TITAN_MODMENU_FRIENDS = "친구목록";
TITAN_MODMENU_TALENTS = "특성";

---  Fran?is  ---
--- by Apsalar ---
if ( GetLocale() == "frFR" ) then
	TITAN_MODMENU_MENU_BARTEXT = "MM";
	TITAN_MODMENU_MENU_TEXT = "ModMenu";
	TITAN_MODMENU_MENU_OPENTEXT = "Ouvrir l'Addon";
	TITAN_MODMENU_MENU_SETUPTEXT= "Configuration de l'Addon";
	TITAN_MODMENU_MENU_SYSTEMTEXT = "Menu Syst\195\168me";
	
	TITAN_MODMENU_SETUP = "Configuration";
	TITAN_MODMENU_TOGGLE = "Activer";
	TITAN_MODMENU_OPEN = "Ouvrir";
	TITAN_MODMENU_CLOSE = "Fermer";
	TITAN_MODMENU_SHOW = "Afficher";
	TITAN_MODMENU_HIDE = "Cacher";
	TITAN_MODMENU_LOCK = "Bloquer";
	TITAN_MODMENU_UNLOCK = "D\195\169bloquer";
	TITAN_MODMENU_HELP = "Aide";
	TITAN_MODMENU_ON = "On";
	TITAN_MODMENU_OFF = "Off";
	TITAN_MODMENU_ENABLE = "Valider";
	TITAN_MODMENU_DISABLE = "D\195\169valider";
	TITAN_MODMENU_RESET = "Reset";
	TITAN_MODMENU_OPTIONS = "Options";
	TITAN_MODMENU_BUTTON = "Bouton";
	TITAN_MODMENU_VIEW = "Voir";
	TITAN_MODMENU_AUTOMATIC = "Automatique";
	TITAN_MODMENU_STATUS = "Status";
	TITAN_MODMENU_DISPLAY = "Affichage";
	TITAN_MODMENU_MINIMAP = "MiniCarte";
end



---   Deutsch    ---
--- by Chieftain ---
---    ReapeR    ---
--- and dan2507  ---
if ( GetLocale() == "deDE" ) then
	TITAN_MODMENU_MENU_BARTEXT = "MM";
	TITAN_MODMENU_MENU_TEXT = "ModMenu";
	TITAN_MODMENU_MENU_OPENTEXT = "Addon \195\182ffnen";
	TITAN_MODMENU_MENU_SETUPTEXT= "Addon konfigurieren";
	TITAN_MODMENU_MENU_SYSTEMTEXT = "System Menu";
	
	TITAN_MODMENU_KEY = "Tastenbelegung";
	TITAN_MODMENU_SETUP = "Einstellungen";
	TITAN_MODMENU_TOGGLE = "Aktivieren";
	TITAN_MODMENU_OPEN = "\195\150ffnen";
	TITAN_MODMENU_CLOSE = "Schlie\195\159";
	TITAN_MODMENU_SHOW = "Zeigen";
	TITAN_MODMENU_HIDE = "Verstecken";
	TITAN_MODMENU_LOCK = "Sperren";
	TITAN_MODMENU_UNLOCK = "Entsperren";
	TITAN_MODMENU_HELP = "Hilfe";
	TITAN_MODMENU_ON = "An";
	TITAN_MODMENU_OFF = "Aus";
	TITAN_MODMENU_ENABLE = "Aktivieren";
	TITAN_MODMENU_DISABLE = "Deaktivieren";
	TITAN_MODMENU_RESET = "Reset";
	TITAN_MODMENU_OPTIONS = "Optionen";
	TITAN_MODMENU_BUTTON = "Schalter";
	TITAN_MODMENU_VIEW = "Ansicht";
	TITAN_MODMENU_AUTOMATIC = "Automatisch";
	TITAN_MODMENU_STATUS = "Status";
	TITAN_MODMENU_DISPLAY = "Anzeigen";
	TITAN_MODMENU_MINIMAP = "MiniMap";
	TITAN_MODMENU_TOGGLEICONTEXT = "Icon/Text Ein-/Ausschalten";
	TITAN_MODMENU_LOGOUT = "Ausloggen";
	TITAN_MODMENU_EXIT = "Spiel verlassen";
	TITAN_MODMENU_EXIT1 = "/beenden";
	TITAN_MODMENU_GM = "Hilfe und GM Men\195\188";
	TITAN_MODMENU_SPELL = "Zauberbuch";
	TITAN_MODMENU_QUEST = "Questbuch";
	TITAN_MODMENU_WORLD = "Weltkarte";
	TITAN_MODMENU_FRIENDS = "Freunde";
	TITAN_MODMENU_TALENTS = "Talente";
	
	TITAN_MODMENU_CAT_BAR = "Aktionsleisten Addons";
	TITAN_MODMENU_CAT_INVENTORY = "Inventar Addons";
	TITAN_MODMENU_CAT_MAP = "Karten Addons";
	TITAN_MODMENU_CAT_TRADESKILL = "Handwerk Addons";
	TITAN_MODMENU_CAT_QUEST = "Quest Addons";
	TITAN_MODMENU_CAT_COMBAT = "Kampf Addons";
	TITAN_MODMENU_CAT_CLASS = "Klassen spezifische Addons";
	TITAN_MODMENU_CAT_PVP = "PvP Addons";
	TITAN_MODMENU_CAT_CHAT = "Chat Addons";
	TITAN_MODMENU_CAT_GUILD = "Gilden Addons";
	TITAN_MODMENU_CAT_FRIEND = "Freundesliste Addons";
	TITAN_MODMENU_CAT_PARTY = "Gruppen Addons";
	TITAN_MODMENU_CAT_RAID = "Raid Addons";
	TITAN_MODMENU_CAT_HANDY = "Wichtige Funktionen";
	TITAN_MODMENU_CAT_EMOTES = "Emotes";
	TITAN_MODMENU_CAT_OTHER = "Weitere Addons ";
	TITAN_MODMENU_CAT_GAMEMENU = "Spiel Menu";
	TITAN_MODMENU_CAT_SYSTEM = "System Menu";
	TITAN_MODMENU_CAT_MMSETTINGS = "Addons Menu Optionen";
end 