MoveAnything_PredefinedCustomFrameList = {
	{ "Separator", "**** BankItems ****" },
	{ "BankItems_Frame", "BankItems Main Frame" },
	{ "BankItems_ContainerFrame1", "BankItems Bag 1" },
	{ "BankItems_ContainerFrame2", "BankItems Bag 2" },
	{ "BankItems_ContainerFrame3", "BankItems Bag 3" },
	{ "BankItems_ContainerFrame4", "BankItems Bag 4" },
	{ "BankItems_ContainerFrame5", "BankItems Bag 5" },
	{ "BankItems_ContainerFrame6", "BankItems Bag 6" },
	{ "Separator", "**** CT_Mod Frames ****" },
		-- These frames don't truly hide and can cause issues
		-- with mouseover frames close to them
	{ "CT_OptionBarFrame", "CT_Mod Options Button" },
	{ "CT_RASetsFrame", "CT_RaidAssist Options Button" },
	{ "Separator", "**** Custom Windows ****" },
	{ "CT_RAMessageFrame", "공격대도우미 메세지창" },
	{ "CT_RA_WarningFrame", "공격대도우미 경고창" },
	{ "ReagentHeavenFrame", "재료천국창" },
	{ "HoTT_Display_NameArea", "Itchy's TargetOfTarget 대상의 대상창" },
	{ "BlinkOnRangeFrame", "Blink의 거리표시창" },
	{ "DruidBarFrame", "드루이드바" },
	{ "GoodInspectFrame", "GoodInspect(훔쳐보기의 대가)창" },
	{ "AllInOneInventoryFrame", "올인원 인벤토리창" },
	{ "AlertFrame", "마법경고 경고메세지"},
	{ "WarningFrame", "마법경고 레이드경고메세지"},
	{ "FishingWatchDragFrame", "낚시도우미 획득량 표시"},
	{ "BlinkHealthTextPlayer", "BlinkHealthText 플레이어 체력 텍스트"},
	{ "BlinkHealthTextTarget", "BlinkHealthText 대상 체력 텍스트"},
	{ "ICU_PopupButton1", "ICU 팝업창"},
	{ "SuperMacroFrame", "SuperMacro 창"},
	{ "MI2_MobHealthFrame", "MobInfo2 체력 텍스트"},
	{ "PetActionBarFrame", "PetActionBarFrame" },
};
