function TitanLocalizeKR()
	TITAN_DEBUG = "<타이탄>";
	TITAN_INFO = "<타이탄>"
	
	TITAN_NA = "N/A";
	TITAN_SECONDS = "초";
	TITAN_MINUTES = "분";
	TITAN_HOURS = "시간";
	TITAN_DAYS = "일";
	TITAN_SECONDS_ABBR = "초";
	TITAN_MINUTES_ABBR = "분";
	TITAN_HOURS_ABBR = "시간";
	TITAN_DAYS_ABBR = "일";
	TITAN_MILLISECOND = "ms";
	TITAN_KILOBYTES_PER_SECOND = "KB/s";
	TITAN_KILOBITS_PER_SECOND = "kbps"
	TITAN_MEGABYTE = "MB";
	
	TITAN_MOVABLE_TOOLTIP = "드래그해서 이동하세요.";

	TITAN_PANEL_ERROR_DUP_PLUGIN = " appears to be registered twice this will cause Titan panel to fail please correct this problem"
	
	TITAN_PANEL = "타이탄 패널";
	TITAN_PANEL_MENU_TITLE = "타이탄 패널";
	TITAN_PANEL_MENU_HIDE = "사용 안함";
	TITAN_PANEL_MENU_CUSTOMIZE = "세부 설정";
	TITAN_PANEL_MENU_SHOW_COLORED_TEXT = "설정된 색상으로 표시";
	TITAN_PANEL_MENU_SHOW_ICON = "아이콘";
	TITAN_PANEL_MENU_SHOW_LABEL_TEXT = "이름표";
	TITAN_PANEL_MENU_AUTOHIDE = "자동 숨김";
	TITAN_PANEL_MENU_BGMINIMAP = "전장 미니맵";
	TITAN_PANEL_MENU_CENTER_TEXT = "가운데 정렬";
	TITAN_PANEL_MENU_DISPLAY_ONTOP = "맨위에 위치";
	TITAN_PANEL_MENU_DISPLAY_BOTH = "양쪽 바 보이기";
	TITAN_PANEL_MENU_DISABLE_PUSH = "화면조절 끄기";
	TITAN_PANEL_MENU_BUILTINS = "내장 애드온";
	TITAN_PANEL_MENU_LEFT_SIDE = "좌측";
	TITAN_PANEL_MENU_RIGHT_SIDE = "우측";
	TITAN_PANEL_MENU_LOAD_SETTINGS = "셋팅 불러오기";
	TITAN_PANEL_MENU_DOUBLE_BAR = "더블 패널";
	TITAN_PANEL_MENU_OPTIONS = "옵션";
	TITAN_PANEL_MENU_PLUGINS = "플러그 인";
	TITAN_PANEL_MENU_VERSION_SHOWN = "플러그인 버전 보기";
	TITAN_PANEL_MENU_DISBALE_FONT = "폰트 조정 끄기";
	TITAN_PANEL_MENU_CATEGORIES = {"일반","전투","정보","인터페이스","전문직업"}
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN = "툴팁 보이기";
	TITAN_PANEL_MENU_CASTINGBAR = "캐스팅 바 이동";

	TITAN_AUTOHIDE_TOOLTIP = "패널 자동숨김(토글)";
	TITAN_AUTOHIDE_MENU_TEXT = "자동숨김";
	
	TITAN_AMMO_FORMAT = "%d";
	TITAN_AMMO_BUTTON_LABEL_AMMO = "탄약: ";
	TITAN_AMMO_BUTTON_LABEL_THROWN = "투척: ";
	TITAN_AMMO_BUTTON_LABEL_AMMO_THROWN = "투사체: ";
	TITAN_AMMO_TOOLTIP = "착용한 투사체 수량";
	TITAN_AMMO_MENU_TEXT = "투사체 수량";
	TITAN_AMMO_THROWN_KEYWORD = "투척";

	TITAN_BAG_FORMAT = "%d/%d";
	TITAN_BAG_BUTTON_LABEL = "가방: ";
	TITAN_BAG_TOOLTIP = "가방 사용량";
	TITAN_BAG_TOOLTIP_HINTS = "모든 가방 열기/닫기 (왼쪽 클릭)";
	TITAN_BAG_MENU_TEXT = "가방 사용량";
	TITAN_BAG_MENU_SHOW_USED_SLOTS = "사용 중인 공간 보기";
	TITAN_BAG_MENU_SHOW_AVAILABLE_SLOTS = "남은 공간 보기";
	TITAN_BAG_MENU_IGNORE_AMMO_POUCH_SLOTS = "투사체 주머니 제외";
	TITAN_BAG_MENU_IGNORE_SHARD_BAGS_SLOTS = "영혼석 가방 제외";
	TITAN_BAG_MENU_IGNORE_PROF_BAGS_SLOTS = "전문직업용 가방 제외";
	TITAN_BAG_SHARD_BAG_NAMES = {"영혼","화산핵 지옥매듭 가방"};
	TITAN_BAG_AMMO_POUCH_NAMES = {"탄약", "화살", "탄띠", "투척", "탄환"};
	TITAN_BAG_PROF_BAG_NAMES = {"마력 깃든 마법매듭 가방","마력 깃든 룬매듭 가방","세나리온 약초 가방","세나리우스의 주머니"};

	TITAN_BGMINIMAP_MENU_TEXT = "전장 미니맵"
	TITAN_BGMINIMAP_TOOLTIP = "전장 미니맵(토글)"

	TITAN_CLOCK_TOOLTIP = "시계";
	TITAN_CLOCK_TOOLTIP_VALUE = "시차: ";
	TITAN_CLOCK_TOOLTIP_HINT1 = "시차 제어판 열기"
	TITAN_CLOCK_TOOLTIP_HINT2 = "(왼쪽 클릭)";
	TITAN_CLOCK_CONTROL_TOOLTIP = "현재 시차 적용값: ";
	TITAN_CLOCK_CONTROL_TITLE = "시차 제어판";
	TITAN_CLOCK_CONTROL_HIGH = "+12";
	TITAN_CLOCK_CONTROL_LOW = "-12";
	TITAN_CLOCK_CHECKBUTTON = "24시간제";
	TITAN_CLOCK_CHECKBUTTON_TOOLTIP = "선택 시 24시간 표기로 전환합니다.";
	TITAN_CLOCK_MENU_TEXT = "시계";
	TITAN_CLOCK_MENU_DISPLAY_ON_RIGHT_SIDE = "우측에 표시";

	TITAN_COORDS_FORMAT = "(%.d, %.d)";
	TITAN_COORDS_BUTTON_LABEL = "위치: ";
	TITAN_COORDS_TOOLTIP = "위치 정보";
	TITAN_COORDS_TOOLTIP_HINTS_1 = "현재 좌표를 채팅창으로 출력";
	TITAN_COORDS_TOOLTIP_HINTS_2 = "(Shift + Left-Click)";
	TITAN_COORDS_TOOLTIP_ZONE = "지역: ";
	TITAN_COORDS_TOOLTIP_SUBZONE = "세부 지역: ";
	TITAN_COORDS_TOOLTIP_PVPINFO = "PvP 정보: ";
	TITAN_COORDS_TOOLTIP_HOMELOCATION = "귀환지";
	TITAN_COORDS_TOOLTIP_INN = "여관: ";
	TITAN_COORDS_MENU_TEXT = "위치 정보";
	TITAN_COORDS_MENU_SHOW_ZONE_ON_PANEL_TEXT = "지역명 보기";
	TITAN_COORDS_MENU_SHOW_COORDS_ON_MAP_TEXT = "월드맵에 좌표 표시";
	TITAN_COORDS_MAP_COORDS_TEXT = "%d, %d";
	TITAN_COORDS_MAP_CURSOR_COORDS_TEXT = "커서 위치: %s";
	TITAN_COORDS_MAP_PLAYER_COORDS_TEXT = "내 위치: %s";

	TITAN_FPS_FORMAT = "%.1f";
	TITAN_FPS_BUTTON_LABEL = "FPS: ";
	TITAN_FPS_MENU_TEXT = "FPS";
	TITAN_FPS_TOOLTIP_CURRENT_FPS = "현재 FPS: ";
	TITAN_FPS_TOOLTIP_AVG_FPS = "평균 FPS: ";
	TITAN_FPS_TOOLTIP_MIN_FPS = "최소 FPS: ";
	TITAN_FPS_TOOLTIP_MAX_FPS = "최대 FPS: ";
	TITAN_FPS_TOOLTIP = "초당 프레임수";

	TITAN_HONOR_BUTTON_LABEL_RANK = RANK..": ";
	TITAN_HONOR_BUTTON_LABEL_HK = "명예 승수: ";
	TITAN_HONOR_BUTTON_LABEL_DK = "불명예 승수: ";
	TITAN_HONOR_TOOLTIP = "PvP 명예 정보";
	TITAN_HONOR_MENU_TEXT = "PvP 명예 정보";

	TITAN_LATENCY_FORMAT = "%d"..TITAN_MILLISECOND;
	TITAN_LATENCY_BANDWIDTH_FORMAT = "%.3f "..TITAN_KILOBYTES_PER_SECOND;
	TITAN_LATENCY_BUTTON_LABEL = "지연: ";
	TITAN_LATENCY_TOOLTIP = "네트워크 상태";
	TITAN_LATENCY_TOOLTIP_LATENCY = "지연 시간: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_IN = "받는 대역폭: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_OUT = "보내는 대역폭: ";
	TITAN_LATENCY_MENU_TEXT = "지연 시간";
	
	TITAN_LOOTTYPE_BUTTON_LABEL = "루팅: ";
	TITAN_LOOTTYPE_FREE_FOR_ALL = "자유 획득";
	TITAN_LOOTTYPE_ROUND_ROBIN = "차례대로 획득";
	TITAN_LOOTTYPE_MASTER_LOOTER = "담당자 획득";
	TITAN_LOOTTYPE_GROUP_LOOT = "주사위 굴림";
	TITAN_LOOTTYPE_NEED_BEFORE_GREED = "착용자 굴림";
	TITAN_LOOTTYPE_TOOLTIP = "루팅 방식";
	TITAN_LOOTTYPE_MENU_TEXT = "루팅 방식";

	TITAN_MEMORY_FORMAT = "%.3f"..TITAN_MEGABYTE;
	TITAN_MEMORY_RATE_FORMAT = "%.3f"..TITAN_KILOBYTES_PER_SECOND;
	TITAN_MEMORY_BUTTON_LABEL = "메모리: ";
	TITAN_MEMORY_TOOLTIP = "사용중인 메모리";
	TITAN_MEMORY_TOOLTIP_CURRENT_MEMORY = "현재: ";
	TITAN_MEMORY_TOOLTIP_INITIAL_MEMORY = "최초: ";
	TITAN_MEMORY_TOOLTIP_INCREASING_RATE = "증가률: ";
	TITAN_MEMORY_TOOLTIP_GC_INFO = "불필요 메모리 정리 정보: ";
	TITAN_MEMORY_TOOLTIP_GC_THRESHOLD = "불필요 메모리 정리 한계값: ";
	TITAN_MEMORY_TOOLTIP_TIME_TO_GC = "불필요 메모리 정리까지 남은 시간: "
	TITAN_MEMORY_MENU_TEXT = "메모리";
	TITAN_MEMORY_MENU_RESET_SESSION = "접속 초기화";
	
	TITAN_MONEY_GOLD = "골드";
	TITAN_MONEY_SILVER = "실버";
	TITAN_MONEY_COPPER = "쿠퍼";
	TITAN_MONEY_FORMAT = "%d"..TITAN_MONEY_GOLD..", %d"..TITAN_MONEY_SILVER..", %d"..TITAN_MONEY_COPPER;
	TITAN_MONEY_MENU_TEXT = "소지금";
	TITAN_MONEY_MENU_RESET_SESSION = "접속 초기화";
	TITAN_MONEY_TOOLTIP = "소지금";
	TITAN_MONEY_TOOLTIP_HINTS = "소지금 나눔 (Left-Click)";
	TITAN_MONEY_TOOLTIP_CURRENT = "현재: ";
	TITAN_MONEY_TOOLTIP_INITIAL = "시작: ";
	TITAN_MONEY_TOOLTIP_EARNED = "획득: ";
	TITAN_MONEY_TOOLTIP_LOST = "사용: ";
	TITAN_MONEY_TOOLTIP_EARNED_HOUR = "시간당 획득량: ";
	TITAN_MONEY_TOOLTIP_LOST_HOUR = "시간당 사용량: ";
	
	TITAN_PERFORMANCE_TOOLTIP = "시스템 성능";
	TITAN_PERFORMANCE_MENU_TEXT = "시스템 성능";
	TITAN_PERFORMANCE_MENU_SHOW_FPS = "FPS";
	TITAN_PERFORMANCE_MENU_SHOW_LATENCY = "지연 시간";
	TITAN_PERFORMANCE_MENU_SHOW_MEMORY = "메모리";

	TITAN_RIDER_HINT = "현재 상태: ";
	TITAN_RIDER_OPTIONS_SHOWSTATE = "사용자 상태 보임";
	TITAN_RIDER_OPTIONS_EQUIP = "착용 아이템";
	TITAN_RIDER_STATES = {"미탑승", "탈것 탑승", "그리폰/와이번 탑승", "배 탑승"};
	TITAN_RIDER_ITEMS = 3;
	TITAN_RIDER_ITEM_NAMES = {nil,"당근 지팡이",nil};
	TITAN_RIDER_ITEM_DESCS = {"미스릴 박차",nil,"하급 조련술"};
	TITAN_RIDER_ITEM_SLOTS = {"신발","장신구1","손"}

	TITAN_TRANS_TOOLTIP = "패널 투명도 설정";
	TITAN_TRANS_TOOLTIP_VALUE = "현재 투명도: ";
	TITAN_TRANS_TOOLTIP_HINT1 = "패널 투명도 설정 제어판 열기";
	TITAN_TRANS_TOOLTIP_HINT2 = "(Left-Click)";
	TITAN_TRANS_CONTROL_TOOLTIP = "투명도: ";
	TITAN_TRANS_CONTROL_TITLE = "투명도";
	TITAN_TRANS_CONTROL_HIGH = "100%";
	TITAN_TRANS_CONTROL_LOW = "0%";
	TITAN_TRANS_MENU_TEXT = "패널 투명도";
	
	TITAN_UISCALE_TOOLTIP = "UI / 패널 크기";
	TITAN_UISCALE_TOOLTIP_VALUE_UI = "UI 크기: ";
	TITAN_UISCALE_TOOLTIP_VALUE_PANEL = "패널 크기: ";
	TITAN_UISCALE_TOOLTIP_VALUE_FONT = "폰트 크기: ";
	TITAN_UISCALE_TOOLTIP_HINT1 = "UI / 패널 크기 제어판 열기";
	TITAN_UISCALE_TOOLTIP_HINT2 = "(Left-Click)";
	TITAN_UISCALE_CONTROL_TOOLTIP_UI = "UI 크기: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_PANEL = "패널 크기: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_FONT = "폰트 크기: ";
	TITAN_UISCALE_CONTROL_TITLE_UI = "UI 크기";
	TITAN_UISCALE_CONTROL_TITLE_PANEL = "패널 크기";
	TITAN_UISCALE_CONTROL_TITLE_FONT = "폰트 크기";
	TITAN_UISCALE_CONTROL_HIGH_UI = "100%";
	TITAN_UISCALE_CONTROL_HIGH_PANEL = "125%";
	TITAN_UISCALE_CONTROL_HIGH_FONT = "200%";
	TITAN_UISCALE_CONTROL_LOW_UI = "64%";
	TITAN_UISCALE_CONTROL_LOW_PANEL = "75%";
	TITAN_UISCALE_CONTROL_LOW_FONT = "50%";
	TITAN_UISCALE_MENU_TEXT = "UI / 패널 / 폰트 크기";
	
	TITAN_VOLUME_TOOLTIP = "소리 설정";
	TITAN_VOLUME_TOOLTIP_VALUE = "주 음량: ";
	TITAN_VOLUME_TOOLTIP_HINT1 = "소리 설정 제어판 열기"
	TITAN_VOLUME_TOOLTIP_HINT2 = "(Left-Click)";
	TITAN_VOLUME_CONTROL_TOOLTIP = "음량: ";
	TITAN_VOLUME_CONTROL_TITLE = "소리 설정";
	TITAN_VOLUME_CONTROL_HIGH = "높음";
	TITAN_VOLUME_CONTROL_LOW = "낮음";
	TITAN_VOLUME_MENU_TEXT = "소리 설정";
	
	TITAN_XP_FORMAT = "%d";
	TITAN_XP_PERCENT_FORMAT = TITAN_XP_FORMAT.." (%.1f%%)";
	TITAN_XP_BUTTON_LABEL_XPHR_LEVEL = "현재 레벨의 시간당 얻은 경험치: ";
	TITAN_XP_BUTTON_LABEL_XPHR_SESSION = "현재 접속의 시간당 얻은 경험치: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_LEVEL = "레벨 업: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_SESSION = "레벨 업: ";
	TITAN_XP_TOOLTIP = "경험치 정보";
	TITAN_XP_TOOLTIP_TOTAL_TIME = "전체 플레이 시간: ";
	TITAN_XP_TOOLTIP_LEVEL_TIME = "현재 레벨 플레이 시간: ";
	TITAN_XP_TOOLTIP_SESSION_TIME = "현재 접속 플레이 시간: ";
	TITAN_XP_TOOLTIP_TOTAL_XP = "다음 레벨까지의 경험치 요구량: ";
	TITAN_XP_TOOLTIP_LEVEL_XP = "현재 레벨에서 얻은 경험치: ";
	TITAN_XP_TOOLTIP_TOLEVEL_XP = "다음 레벨까지의 필요 경험치: ";
	TITAN_XP_TOOLTIP_SESSION_XP = "현재 접속에서 얻은 경험치: ";
	TITAN_XP_TOOLTIP_XPHR_LEVEL = "현재 레벨의 시간당 얻은 경험치: ";
	TITAN_XP_TOOLTIP_XPHR_SESSION = "현재 접속의 시간당 얻은 경험치: ";
	TITAN_XP_TOOLTIP_TOLEVEL_LEVEL = "레벨 업 (레벨 대비): ";
	TITAN_XP_TOOLTIP_TOLEVEL_SESSION = "레벨 업 (접속 대비): ";
	TITAN_XP_MENU_TEXT = "경험치";
	TITAN_XP_MENU_SHOW_XPHR_THIS_LEVEL = "현재 레벨의 시간당 얻은 경험치";
	TITAN_XP_MENU_SHOW_XPHR_THIS_SESSION = "현재 접속의 시간당 얻은 경험치";
	TITAN_XP_MENU_RESET_SESSION = "접속 초기화";
	
	TITAN_REGEN_MENU_TEXT 		= "회복"
	TITAN_REGEN_MENU_TOOLTIP_TITLE	= "회복률"
	TITAN_REGEN_MENU_SHOW1 		= "보기"
	TITAN_REGEN_MENU_SHOW2 		= "HP"
	TITAN_REGEN_MENU_SHOW3 		= "MP"
	TITAN_REGEN_MENU_SHOW4		= "퍼센트로"
	TITAN_REGEN_BUTTON_TEXT_HP 		= "HP: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_HP_PERCENT 	= "HP: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP 		= " MP: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP_PERCENT 	= " MP: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP1 		= "체력: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP2 		= "마나: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP3 		= "최고 HP 회복률: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP4 		= "최저 HP 회복률: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP5 		= "최고 MP 회복률: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP6 		= "최저 MP 회복률: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP7		= "최근 전투에서의 MP회복률 : \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..GREEN_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE.."%%)";

	TITAN_ITEMBONUSES_TEXT = "아이템 보너스";
	TITAN_ITEMBONUSES_DISPLAY_NONE = "표시 안함";
	TITAN_ITEMBONUSES_SHORTDISPLAY = "간결한 텍스트 표기";
	TITAN_ITEMBONUSES_BONUSSCANNER_MISSING = "보너스스캐너 애드온이 없습니다.";

	TITAN_ITEMBONUSES_CAT_ATT = "속성";
	TITAN_ITEMBONUSES_CAT_RES = "저항";
	TITAN_ITEMBONUSES_CAT_SKILL = "스킬";
	TITAN_ITEMBONUSES_CAT_BON = "근접 & 원거리 전투";
	TITAN_ITEMBONUSES_CAT_SBON = "주문";
	TITAN_ITEMBONUSES_CAT_OBON = "체력과 마나";

	TITAN_HONORPLUS_BUTTON_LABEL_RANK = RANK..": ";
	TITAN_HONORPLUS_CLASSINDEX = {
		["Druid"]   = 1,
		["Hunter"]  = 2,
		["Mage"]    = 3,
		["Paladin"] = 4,
		["Priest"]  = 5,
		["Rogue"]   = 6,
		["Shaman"]  = 7,
		["Warlock"] = 8,
		["Warrior"] = 9,
		["드루이드"]   = 1,
		["사냥꾼"]  = 2,
		["마법사"]    = 3,
		["성기사"] = 4,
		["사제"]  = 5,
		["도적"]   = 6,
		["주술사"]  = 7,
		["흑마법사"] = 8,
		["전사"] = 9,
	};
	
	TITAN_HONORPLUS_BUTTON_LABEL_HK = "명예 승수: ";
	TITAN_HONORPLUS_BUTTON_LABEL_DK = "불명예 승수: ";
	TITAN_HONORPLUS_TOOLTIP = "PVP 명예 정보";
	TITAN_HONORPLUS_TOOLTIP_THISWEEK = "이번 주";
	TITAN_HONORPLUS_MENU_TEXT = "명예";
	TITAN_HONORPLUS_MENU_CALCTODAY = "오늘의 명예승수 계산 애드온";
	TITAN_HONORPLUS_MENU_SCT = "전투 메시지 확장 기능에 디스플레이 하기";
	TITAN_HONORPLUS_MENU_OPIUM = "Opium 지원";
	TITAN_HONORPLUS_MENU_SCOREBOARDCLASSCOLORSYMBOL = "스코어보드에 직업심볼을 색깔로 표시";
	TITAN_HONORPLUS_MENU_SCOREBOARDCLASSCOLORLIST = "스코어보드에 직업이름을 색깔로 표시";
	TITAN_HONORPLUS_MENU_SCOREBOARDKILLS = "스코어보드에 오늘의 예상 명예 승수 보여주기";
	TITAN_HONORPLUS_MENU_PRINTBONUS = "채팅창에 명예 보너스 표시하기";
	TITAN_HONORPLUS_MENU_TOOLTIP = "툴팁 정보 표시";
	TITAN_HONORPLUS_MENU_SORTBYHONOR = "명예 수치로 정렬";
	TITAN_HONORPLUS_MENU_SORTBYKILLS = "명예 승수로 정렬";
	TITAN_HONORPLUS_ESTIMATED = "%s 사망, [현재 명예점수 %d], 순위: %s. [예상 명예점수: %d]";
	TITAN_HONORPLUS_BONUSHONORGAINED = "보너스 명예 점수를 획득했습니다: %s";
	TITAN_HONORPLUS_BONUS = "보너스 명예 점수";
	TITAN_HONORPLUS_PROGRESS = "계급 위치";
	TITAN_HONORPLUS_TODAYHONOR = "오늘의 예상 명예 점수";
	TITAN_HONORPLUS_KILLS = "명예 승수";
	TITAN_HONORPLUS_DEATHS = "죽은 수";
	TITAN_HONORPLUS_TOTAL = "합계";
	TITAN_HONORPLUS_TOP15 = "톱 15";
	TITAN_HONORPLUS_PVPSTATS = "PvP 통계";
	TITAN_HONORPLUS_NOKILLS = "없음";
	TITAN_HONORPLUS_HINT = "힌트: 세부 정보를 보기 위해선 라이트 클릭 하세요.";
	TITAN_HONORPLUS_HINT_TOOLTIP = "세부 정보(Left click)";
	TITAN_HONORPLUS_TOOLTIP_TODAYSKILLS = "오늘의 명예 승수입니다.";
	TITAN_HONORPLUS_KILLEDTODAY = "오늘 취득한 명예 승수";
	TITAN_HONORPLUS_MENU_AUTORELEASE = "자동 기능";
	TITAN_HONORPLUS_MENU_AUTOJOINBG = "전장 자동입장";
	TITAN_HONORPLUS_AUTOJOINBG = "10초 안에 전장에 자동입장 합니다.";
	TITAN_HONORPLUS_AUTOJOINBG_CANCEL = "전장 입장을 취소합니다.";
	TITAN_HONORPLUS_AUTOJOINBG_DONE = "지금 전장에 입장합니다. 행운을 빕니다!";

	--Titan Repair
	REPAIR_LOCALE = {
		pattern = "내구도 (%d+) / (%d+)$",
		menu = "내구도 정보",
		tooltip = "내구도 정보",
		button = "내구도: ",
		percentage = "퍼센트로 보기",
		itemname = "아이템 이름 보기",
		undamaged = "피해 없는 아이템 보기",
		nothing = "피해 손실이 없습니다.",
		confirmation = "모든 손실아이템의 수리를 원하십니까?",
		popup = "수리 팝업 보기",
		repinventory = "인벤토리 아이템 수리",
		showinventory = "인벤토리 데미지 계산",
	};

	TITAN_PLUGINS_MENU_TITLE = "플러그 인";
	
	CUSTOMIZATION_FEATURE_COMING_SOON = "관련 메뉴가 없습니다....";
end

function Localize()
	TitanLocalizeEN();
	
	local locale = GetLocale();
	if ( locale == "koKR" ) then
		TitanLocalizeKR();
	end
end

function LocalizeFrames()
	-- Put all locale specific UI adjustments here
end